version: '3.1'
type: CONFIG
id: 979e76b3-696b-4a56-a8fe-e5ac365f57c6
summary:
  creation_date: '2022-12-17 12:25:33.911'
  update_date: '2023-05-28 00:12:10.173'
  target_filepath: ./record.yml
  log_filepath: log.log
  log_level: INFO
  notification_filepath: '@/notification.yml'
  crowdsourcing_platform: N4U
  crowdsourcing_strict: false
  crowdsourcing_limit: 3000
  crowdsourcing_worker_accuracy: 1.0
  ngraph_construction: DIST
  ngraph_params:
    k: 10
    dist: 1.0
    enable_pseudo_dist: true
  inference_mode: BAYESIAN
workflow:
- name: LOAD_FASTTEXT
  filepath: '@/fasttext/cc.ja.300.bin'
  everytime: true
- name: DIST_TRAINING
  filepath: ./record.yml
  use_crowdsourcing: false
- name: SAVE_MODEL
  filepath: ./metric.keras
  everytime: false
- name: LOAD_MODEL
  filepath: ./metric.keras
  everytime: true
- name: GENERATE_PARAMS
  filepath: ./record.yml
  use_crowdsourcing: false
  distribution_type: MIXED_GAUSSIAN
  image_title: Bibliography Japan 10k
  image_dirpath: ./image
- name: SAVE_PARAMS
  filepath: ./params.yml
